DROP TABLE IF EXISTS teachers;

DROP TABLE IF EXISTS course_items;

DROP TABLE IF EXISTS dashboard;

DROP TABLE IF EXISTS gallery;

DROP TABLE IF EXISTS branches;

DROP TABLE IF EXISTS certificates;

DROP TABLE IF EXISTS courses;