// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.3
// source: gallery.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GalleryService_Create_FullMethodName  = "/proto.GalleryService/Create"
	GalleryService_Update_FullMethodName  = "/proto.GalleryService/Update"
	GalleryService_Delete_FullMethodName  = "/proto.GalleryService/Delete"
	GalleryService_GetById_FullMethodName = "/proto.GalleryService/GetById"
	GalleryService_GetList_FullMethodName = "/proto.GalleryService/GetList"
)

// GalleryServiceClient is the client API for GalleryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GalleryServiceClient interface {
	Create(ctx context.Context, in *CreateGallery, opts ...grpc.CallOption) (*Void, error)
	Update(ctx context.Context, in *UpdateGallery, opts ...grpc.CallOption) (*Void, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GalleryRes, error)
	GetList(ctx context.Context, in *GetListGalleryReq, opts ...grpc.CallOption) (*GetListGalleryRes, error)
}

type galleryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGalleryServiceClient(cc grpc.ClientConnInterface) GalleryServiceClient {
	return &galleryServiceClient{cc}
}

func (c *galleryServiceClient) Create(ctx context.Context, in *CreateGallery, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, GalleryService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) Update(ctx context.Context, in *UpdateGallery, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, GalleryService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, GalleryService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GalleryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GalleryRes)
	err := c.cc.Invoke(ctx, GalleryService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) GetList(ctx context.Context, in *GetListGalleryReq, opts ...grpc.CallOption) (*GetListGalleryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListGalleryRes)
	err := c.cc.Invoke(ctx, GalleryService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalleryServiceServer is the server API for GalleryService service.
// All implementations must embed UnimplementedGalleryServiceServer
// for forward compatibility.
type GalleryServiceServer interface {
	Create(context.Context, *CreateGallery) (*Void, error)
	Update(context.Context, *UpdateGallery) (*Void, error)
	Delete(context.Context, *ById) (*Void, error)
	GetById(context.Context, *ById) (*GalleryRes, error)
	GetList(context.Context, *GetListGalleryReq) (*GetListGalleryRes, error)
	mustEmbedUnimplementedGalleryServiceServer()
}

// UnimplementedGalleryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGalleryServiceServer struct{}

func (UnimplementedGalleryServiceServer) Create(context.Context, *CreateGallery) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGalleryServiceServer) Update(context.Context, *UpdateGallery) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedGalleryServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGalleryServiceServer) GetById(context.Context, *ById) (*GalleryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedGalleryServiceServer) GetList(context.Context, *GetListGalleryReq) (*GetListGalleryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedGalleryServiceServer) mustEmbedUnimplementedGalleryServiceServer() {}
func (UnimplementedGalleryServiceServer) testEmbeddedByValue()                        {}

// UnsafeGalleryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GalleryServiceServer will
// result in compilation errors.
type UnsafeGalleryServiceServer interface {
	mustEmbedUnimplementedGalleryServiceServer()
}

func RegisterGalleryServiceServer(s grpc.ServiceRegistrar, srv GalleryServiceServer) {
	// If the following call pancis, it indicates UnimplementedGalleryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GalleryService_ServiceDesc, srv)
}

func _GalleryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGallery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Create(ctx, req.(*CreateGallery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGallery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Update(ctx, req.(*UpdateGallery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListGalleryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalleryService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).GetList(ctx, req.(*GetListGalleryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GalleryService_ServiceDesc is the grpc.ServiceDesc for GalleryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GalleryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GalleryService",
	HandlerType: (*GalleryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GalleryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GalleryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GalleryService_Delete_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _GalleryService_GetById_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _GalleryService_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gallery.proto",
}
