// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: gallery.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GalleryServiceClient is the client API for GalleryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GalleryServiceClient interface {
	Create(ctx context.Context, in *CreateGallery, opts ...grpc.CallOption) (*Void, error)
	Update(ctx context.Context, in *UpdateGallery, opts ...grpc.CallOption) (*Void, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GalleryRes, error)
	GetList(ctx context.Context, in *GetListGalleryReq, opts ...grpc.CallOption) (*GetListGalleryRes, error)
}

type galleryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGalleryServiceClient(cc grpc.ClientConnInterface) GalleryServiceClient {
	return &galleryServiceClient{cc}
}

func (c *galleryServiceClient) Create(ctx context.Context, in *CreateGallery, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.GalleryService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) Update(ctx context.Context, in *UpdateGallery, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.GalleryService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.GalleryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*GalleryRes, error) {
	out := new(GalleryRes)
	err := c.cc.Invoke(ctx, "/proto.GalleryService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galleryServiceClient) GetList(ctx context.Context, in *GetListGalleryReq, opts ...grpc.CallOption) (*GetListGalleryRes, error) {
	out := new(GetListGalleryRes)
	err := c.cc.Invoke(ctx, "/proto.GalleryService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalleryServiceServer is the server API for GalleryService service.
// All implementations must embed UnimplementedGalleryServiceServer
// for forward compatibility
type GalleryServiceServer interface {
	Create(context.Context, *CreateGallery) (*Void, error)
	Update(context.Context, *UpdateGallery) (*Void, error)
	Delete(context.Context, *ById) (*Void, error)
	GetById(context.Context, *ById) (*GalleryRes, error)
	GetList(context.Context, *GetListGalleryReq) (*GetListGalleryRes, error)
	mustEmbedUnimplementedGalleryServiceServer()
}

// UnimplementedGalleryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGalleryServiceServer struct {
}

func (UnimplementedGalleryServiceServer) Create(context.Context, *CreateGallery) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGalleryServiceServer) Update(context.Context, *UpdateGallery) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedGalleryServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGalleryServiceServer) GetById(context.Context, *ById) (*GalleryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedGalleryServiceServer) GetList(context.Context, *GetListGalleryReq) (*GetListGalleryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedGalleryServiceServer) mustEmbedUnimplementedGalleryServiceServer() {}

// UnsafeGalleryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GalleryServiceServer will
// result in compilation errors.
type UnsafeGalleryServiceServer interface {
	mustEmbedUnimplementedGalleryServiceServer()
}

func RegisterGalleryServiceServer(s grpc.ServiceRegistrar, srv GalleryServiceServer) {
	s.RegisterService(&GalleryService_ServiceDesc, srv)
}

func _GalleryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGallery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GalleryService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Create(ctx, req.(*CreateGallery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGallery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GalleryService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Update(ctx, req.(*UpdateGallery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GalleryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GalleryService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalleryService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListGalleryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalleryServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GalleryService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalleryServiceServer).GetList(ctx, req.(*GetListGalleryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GalleryService_ServiceDesc is the grpc.ServiceDesc for GalleryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GalleryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GalleryService",
	HandlerType: (*GalleryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GalleryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GalleryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GalleryService_Delete_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _GalleryService_GetById_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _GalleryService_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gallery.proto",
}
